// Custom image loader for next-image-export-optimizer
// Maps next/image requests to the pre-generated optimized WebP files at build time
export default function imageLoader({
  src,
  width,
}: {
  src: string;
  width: number;
}): string {
  // In development, serve the original image
  if (process.env.NODE_ENV === 'development') {
    return src;
  }

  const lastSlash = src.lastIndexOf('/');
  const directory = src.substring(0, lastSlash);
  const filename = src.substring(lastSlash + 1);
  const baseName = filename.substring(0, filename.lastIndexOf('.'));

  // Sizes generated by next-image-export-optimizer
  const sizes = [10, 32, 48, 64, 96, 128, 256, 384, 640, 750, 828, 1080, 1200, 1920, 2048, 3840];
  const nearest = sizes.find(s => s >= width) ?? sizes[sizes.length - 1];

  return `${directory}/nextImageExportOptimizer/${baseName}-opt-${nearest}.WEBP`;
}
